### ISSUE TITLE
Loan Product API

### ISSUE THREAD

**Issue by maektwain** [upscaletech/gateway#4]
When a consumer with partner authority gets created he needs to create loan products which a partner is going to offer these will be done once a DB tenant is created inside the finocial which we are going to create when a partner is registered 
1. Before Creating Loan Product API we need to finish the issue #3 
2. Developing an automated services like a message which receives a message and says ok create a db and then returns the result in meanwhile 

Loan Product 

When a user or partner accesses his api first thing he needs to do is to upload the loan product with minimum structure such as providing principal, kind of loan and configurations around the loan product which is going to be available at the side of consume 

`POST /api/partner/loanproducts`

``` json
{ 
     "name":"Loan Product Sample",
     "tenure":"12"
     using the existing domain

}

```

we will store everything on the Gateway as of now

**Comment by anuragmath** [comment]
I understand the need of an API for creation of a loan product after partner(tenant) creation, but i think it wont be necessary to create this api for partne in our gateway, as i think partners will have access to our backend so they can create a product from there easily.

**Comment by maektwain** [comment]
Yeah but providing them two different sets of api is not good i am thinking of using single set of api which will be accessed through gateway only
